package br.ufrj.cos482.domain.enumeration;

/**
 * The Funcoes enumeration.
 */
public enum Funcoes {
    CADASTRAR_ALUNO,DESCADASTRAR_ALUNO,CADASTRAR_PROFESSOR,DESCADASTRAR_PROFESSOR,CADASTRAR_SECRETARIO,DESCADASTRAR_SECRETARIO,EMITIR_DIPLOMA,VALIDAR_DOCUMENTO,VERIFICAR_INFORMACOES_ALUNO,ATUALIZAR_MATRICULA,ENVIAR_DOCUMENTO_MESTRADO,REMOVER_DOCUMENTO_MESTRADO,ENVIAR_DOCUMENTO_DOUTORADO,REMOVER_DOCUMENTO_DOUTORADO
}
